USE HOTELBOOKINGDB
GO

-- Insertar roles
INSERT INTO ROLES (NAME) VALUES ('Agente de Viajes');
INSERT INTO ROLES (NAME) VALUES ('Viajero');

-- Insertar permisos
INSERT INTO PERMISSIONS (NAME) VALUES ('Gestionar Hoteles');
INSERT INTO PERMISSIONS (NAME) VALUES ('Realizar Reservas');

-- Asignar permisos a roles
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, 1); -- Agente de Viajes puede gestionar hoteles
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (2, 2); -- Viajero puede realizar reservas

-- Insertar usuarios
INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLEID) 
VALUES ('Carlos', 'Pérez', 'agente@ejemplo.com', '$2a$11$OSiP6TZdNHEJN.cq38lA8OhF0JYC4/ghMOq7Zsg9iXFx1M2B5bti.', 1);
INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLEID) 
VALUES ('María', 'Gómez', 'viajero@ejemplo.com', '$2a$11$OSiP6TZdNHEJN.cq38lA8OhF0JYC4/ghMOq7Zsg9iXFx1M2B5bti.', 2);

-- Insertar ciudades en Colombia
INSERT INTO CITIES (NAME) VALUES ('Bogotá');
INSERT INTO CITIES (NAME) VALUES ('Medellín');
INSERT INTO CITIES (NAME) VALUES ('Cartagena');

-- Insertar hoteles
INSERT INTO HOTELS (NAME, ADDRESS, CITYID, COMMISSIONRATE) 
VALUES ('Hotel El Dorado', 'Calle 26 # 69D-91', 1, 10.00);
INSERT INTO HOTELS (NAME, ADDRESS, CITYID, COMMISSIONRATE) 
VALUES ('Hotel Poblado Plaza', 'Carrera 43A # 4 Sur-75', 2, 12.50);

-- Asignar hotel al agente de viajes
INSERT INTO AGENTHOTELS (USERID, HOTELID) VALUES (1, 1);

-- Insertar tipos de habitación
INSERT INTO ROOMTYPES (NAME) VALUES ('Individual');
INSERT INTO ROOMTYPES (NAME) VALUES ('Doble');

-- Insertar habitaciones
INSERT INTO ROOMS (HOTELID, ROOMTYPEID, BASECOST, TAXES, LOCATION) 
VALUES (1, 1, 200000.00, 30000.00, 'Piso 1');
INSERT INTO ROOMS (HOTELID, ROOMTYPEID, BASECOST, TAXES, LOCATION) 
VALUES (1, 2, 350000.00, 50000.00, 'Piso 2');

-- Insertar tipos de documento y géneros
INSERT INTO DOCUMENTTYPES (NAME) VALUES ('Cédula de Ciudadanía');
INSERT INTO DOCUMENTTYPES (NAME) VALUES ('Pasaporte');
INSERT INTO GENDERS (NAME) VALUES ('Masculino');
INSERT INTO GENDERS (NAME) VALUES ('Femenino');

-- Insertar reserva
INSERT INTO RESERVATIONS (ROOMID, USERID, CHECKINDATE, CHECKOUTDATE, GUESTCOUNT, CITYID, TOTALCOST)
VALUES (1, 2, '2025-02-10', '2025-02-15', 1, 1, 230000.00);

-- Insertar huésped
INSERT INTO GUESTS (RESERVATIONID, FIRSTNAME, LASTNAME, BIRTHDATE, GENDERID, DOCUMENTTYPEID, DOCUMENTNUMBER, EMAIL, PHONE)
VALUES (1, 'María', 'Gómez', '1990-05-05', 2, 1, '1234567890', 'viajero@ejemplo.com', '320-456-7890');

-- Insertar contacto de emergencia
INSERT INTO EMERGENCYCONTACTS (RESERVATIONID, FULLNAME, PHONE)
VALUES (1, 'Carlos Pérez', '301-654-3210');

