USE HOTELBOOKINGDB;
GO
-- Insertar roles
INSERT INTO ROLES (NAME) VALUES ('Agente de Viajes');
INSERT INTO ROLES (NAME) VALUES ('Viajero');

-- Insertar permisos
INSERT INTO PERMISSIONS (NAME) VALUES 
('ListUsers'),
('CreateUsers'),
('UpdateUser'),
('ChangeStateUser'),
('DeleteUser'),
('ListHotels'),
('GetHotelById'),
('CreateHotelRooms'),
('CreateHotel'),
('AssignRoom'),
('UpdateHotel'),
('ChangeStateHotel'),
('DeleteHotel'),
('ListReservations'),
('CreateReservation'),
('ListRoles'),
('GetRoleById'),
('ListRooms'),
('CreateRoom'),
('UpdateRoom'),
('ChangeStateRoom'),
('DeleteRoom'),
('ListRoomTypes');

-- Asignar permisos a Agente de Viajes
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ListHotels'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'CreateHotelRooms'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'CreateHotel'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'AssignRoom'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'UpdateHotel'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ChangeStateHotel'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'DeleteHotel'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ListRooms'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'CreateRoom'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'UpdateRoom'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ChangeStateRoom'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'DeleteRoom'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ListReservations'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (1, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'GetHotelById'));

-- Asignar permisos a Viajero
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (2, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ListHotels'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (2, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'GetHotelById'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (2, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ListRooms'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (2, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ListRoomTypes'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (2, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'ListReservations'));
INSERT INTO ROLEPERMISSIONS (ROLEID, PERMISSIONID) VALUES (2, (SELECT PERMISSIONID FROM PERMISSIONS WHERE NAME = 'CreateReservation'));

-- Insertar usuarios con roles
INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLEID) 
VALUES ('Carlos', 'Pérez', 'agente@gmail.com', '$2a$11$OSiP6TZdNHEJN.cq38lA8OhF0JYC4/ghMOq7Zsg9iXFx1M2B5bti.', 1); -- Agente de Viajes

INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLEID) 
VALUES ('María', 'Gómez', 'viajero@gmail.com', '$2a$11$OSiP6TZdNHEJN.cq38lA8OhF0JYC4/ghMOq7Zsg9iXFx1M2B5bti.', 2); -- Viajero



-- Insertar ciudades en Colombia
INSERT INTO CITIES (NAME) VALUES ('Bogotá'), ('Medellín'), ('Cartagena');

-- Insertar hoteles
INSERT INTO HOTELS (NAME, ADDRESS, CITYID, COMMISSIONRATE) 
VALUES 
('Hotel El Dorado', 'Calle 26 # 69D-91', 1, 10.00),
('Hotel Poblado Plaza', 'Carrera 43A # 4 Sur-75', 2, 12.50);

-- Asignar hotel al agente de viajes
INSERT INTO USERHOTELS (USERID, HOTELID) VALUES (1, 1);

-- Insertar tipos de habitación
INSERT INTO ROOMTYPES (NAME) 
VALUES ('Individual'),('Doble'),('Triple'),('Suite'),('Presidencial');


-- Insertar habitaciones
INSERT INTO ROOMS (HOTELID, ROOMTYPEID, CAPACITY, BASECOST, TAXES, LOCATION) 
VALUES 
(1, 1, 1, 200000.00, 30000.00, 'Piso 1'),
(1, 2, 2, 350000.00, 50000.00, 'Piso 2');

-- Insertar tipos de documento y géneros
INSERT INTO DOCUMENTTYPES (NAME) VALUES ('Cédula de Ciudadanía'), ('Pasaporte');
INSERT INTO GENDERS (NAME) VALUES ('Masculino'), ('Femenino');

-- Insertar reserva
INSERT INTO RESERVATIONS (ROOMID, USERID, CHECKINDATE, CHECKOUTDATE)
VALUES (1, 2, '2025-02-10', '2025-02-15');

-- Insertar huésped
INSERT INTO GUESTS (RESERVATIONID, FIRSTNAME, LASTNAME, BIRTHDATE, GENDERID, DOCUMENTTYPEID, DOCUMENTNUMBER, EMAIL, PHONE)
VALUES (1, 'María', 'Gómez', '1990-05-05', 2, 1, '1234567890', 'viajero@ejemplo.com', '320-456-7890');

-- Insertar contacto de emergencia
INSERT INTO EMERGENCYCONTACTS (RESERVATIONID, FULLNAME, PHONE)
VALUES (1, 'Carlos Pérez', '301-654-3210');

-- Ver todos los roles
SELECT * FROM ROLES;

-- Ver todos los permisos
SELECT * FROM PERMISSIONS;

-- Ver la asignación de permisos a roles
SELECT * FROM ROLEPERMISSIONS;

-- Ver todos los usuarios
SELECT * FROM USERS;

-- Ver todas las ciudades
SELECT * FROM CITIES;

-- Ver todos los hoteles
SELECT * FROM HOTELS;

-- Ver la asignación de hoteles a usuarios
SELECT * FROM USERHOTELS;

-- Ver todos los tipos de habitación
SELECT * FROM ROOMTYPES;

-- Ver todas las habitaciones
SELECT * FROM ROOMS;

-- Ver todos los tipos de documento
SELECT * FROM DOCUMENTTYPES;

-- Ver todos los géneros
SELECT * FROM GENDERS;

-- Ver todas las reservas
SELECT * FROM RESERVATIONS;

-- Ver todos los huéspedes
SELECT * FROM GUESTS;

-- Ver todos los contactos de emergencia
SELECT * FROM EMERGENCYCONTACTS;

SELECT U.USERID,
    U.FIRSTNAME + ' ' + U.LASTNAME AS UserName,  -- Concatenar nombres
    R.NAME AS RoleName,
    P.NAME AS PermissionName
FROM USERS U
JOIN ROLES R ON U.ROLEID = R.ROLEID
JOIN ROLEPERMISSIONS RP ON R.ROLEID = RP.ROLEID
JOIN PERMISSIONS P ON RP.PERMISSIONID = P.PERMISSIONID
ORDER BY UserName, PermissionName;

SELECT 
    c.CITYID,
    c.NAME AS CityName,
    h.HOTELID,
    h.NAME AS HotelName,
    h.ADDRESS,
    h.COMMISSIONRATE,
    h.STATE AS HotelState,
    r.ROOMID,
    rt.NAME AS RoomType,
    r.CAPACITY,
    r.BASECOST,
    r.TAXES,
    r.STATE AS RoomState
FROM HOTELS h
JOIN CITIES c ON h.CITYID = c.CITYID
JOIN ROOMS r ON h.HOTELID = r.HOTELID
JOIN ROOMTYPES rt ON r.ROOMTYPEID = rt.ROOMTYPEID
ORDER BY c.NAME, h.NAME, r.CAPACITY




